### ISSUE TITLE
define and implement new project structure

### ISSUE THREAD

**Issue by msaraga** [MetPX/sarrac#46]

**Comment by petersilva** [comment]
Please define what the new structure will be.  Once the HPC mirroring post corruption thing ( #36)  is out of the way, it would be a good time for something like this.

**Comment by petersilva** [comment]
@dalumas your comments welcome.

**Comment by dalumas** [comment]
Filesystem Hierarchy Standard exists for Linux.

Folder descriptions can be found here:
[](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard)

**Comment by dalumas** [comment]
https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

**Comment by msaraga** [comment]
Regarding project structure, I had something as follows in mind:
```
sarrac/ : top-level dir

sarrac/src/ : *.c, core application code, including libsrshim.c

sarrac/include/ : *.h, module headers and uthash.h

sarrac/test/ : *.c, test files divided by test type
    sarrac/test/unit/ --> testing individual functions (long-term goal..?)
    sarrac/test/integration/ --> testing individual subsystems 
    sarrac/test/system/ --> simple flow test analog
            (checking system-wide functionality. and interoperability with python implementation)

sarrac/docs/ : C implementation specific documentation?
sarrac/eg/ : example configuration files (for testing, template purposes)

sarrac/obj/ : object files (not tracked with git)
sarrac/bin/ : app binaries (not tracked with git)
sarrac/debian/ : debian packaging stuff..

sarrac/Makefile : single Makefile for entire project, building managed from here
sarrac/README.rst : project README
sarrac/LICENCE : main project licence
    (instead of having the same one at the top of most files, exceptions will be marked as such)
sarrac/Doxyfile : doxygen configuration file
```

**Comment by petersilva** [comment]
unit testing normally refers to complete files... this terminology misuse then infects with mis-application of the word "integration" testing... 

what is called *unit* should use some other word... "function" ? "sub-unit" ? :
```

sarrac/test/sub-unit/   --> testing individual functions.
sarrac/test/unit   ---> testing complete files/subsystems. (was called integration above)
   the existing *test.c files go in unit/
sarrac/test/integration --> hooking files/subsystems together.... flow test could be here.

```

in the python implementation, the *eg/* directory is called *examples/* prefer to use that for uniformity.

if trying to inspire from FHS, then *libsrshim.so* and *libsarra.so* would go in *lib/*   

@dalumas the FHS refers to installed directory trees, the debian packaging already installs with FHS compliance.  The standardization examples being sought are for package source code and build trees.

**Comment by msaraga** [comment]
Sounds good!

**Comment by dalumas** [comment]
@petersilva FHS can still be used as a guidance for the build process which will make things easier for packaging and installation. Placing binaries inside a folder name foo does not help.

From the suggested scheme, It's missing sarrac/lib.

**Comment by petersilva** [comment]
fine for sarrac/lib... If we are following FHS, then should be have usr/ as the only top level directory and src/, include/, bin/, lib/ , share/doc, go under there... I'm not recommending that, I'm pointing out a reason why source and destination trees are different.  Also FHS isn't the canonical, always correct thing either, as in Sarracenia, we adopted the newer XDG Base Directory Standard, rather than FHS for certain parts of the tree.

History of Some Linux File Trees
------------------------------------------- 

FHS also kind of conflicts with XDG Base Directory Specification ( 
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html )  which is what is implemented by the appdirs dependency.  XDG is a newer standard than FHS... 

In the stone age, daemons (and everything else) used be to run by root, and data files for daemons were in /var mostly.  over the past twenty years, folks evolved the recommendation to never run daemons as root, but always create a user (and often a group) for the user to run the service, and only give the user the right to modify what they must (principle of least privilege.)  the config files were stored in /etc.
This had many problems where daemons etc... would want huge /var file systems, whereas when things were running as users, and generally real apps, the sysadmins wanted separate file systems ... /apps, or /data, or something else entirely.

In the same stone age, there was no standard on preference/configuration files for users, basically people would put a hidden file (that starts with a .) in their home, and all their settings were in there.
It got messy.  So you had a standard of one rule for root stuff, (a hierachy in /etc) and another
rule for user stuff ( anything starting with a dot in the home.) 

Around twenty-five years ago, XDG Base... basically a group trying to make peace between Gnome and KDE, and X in general, came out with a standard for how to store user preferences (.config) and data (.cache), and they ended up with a something that makes the trees for users and admins similar.

The observation in Sarracenia was to put the *best practice* of creating a user for each application together with the storage standard XDG open group, to just end up using that standard for the *system* preferences, which makes everything far more consistent (users run sr_ processes under their account, the system runs them under the *sarra* account.)

This culminated in one team disagreeig with us, forcing placement of all files under /etc, and replacing the init files so that it would look in /etc. (this is how the wxapps servers are set up.) ...  which is a royal pain... their rationale was FHS compliance.  The XDG_DATA_DIRS, and XDG_DATA_DIRS ...
all contradict FHS, though you will hear others say that XDG stuff is for desktop apps, and it really doesn't conflict, you're just supposed to do completely different trees for root vs. every other user (two trees to implement for everything.) and implement arbitrary permissions (chowning bits of /etc and /var to *sarra* in order to permit the *system* style to actually work.) Sarracenia actively chose XDG over FHS, and that's why the logs are where they are, and the preference files are where they are.  Some will find this choice *wrong*  No particular point to this digression, other than to provide background.

**Comment by petersilva** [comment]
If you look at the Steam client (yes, the gaming thing...) look at how their files are laid out... it's pure XDG.

**Comment by petersilva** [comment]
umm... I feel bad making people read that stuff... short version: the proposed tree sounds fine. ;-)

**Comment by msaraga** [comment]
When updating project structure, will also go over file headers.. Move licenses to LICENSE file and contributions listings to CREDITS (following the Linux kernel tree org)
Will also add a MAINTAINERS file to facilitate contacts for issues not appropriate for the github issue tracker

**Comment by petersilva** [comment]
re-opened due to #69 do not understand what is happenning ther, but I guess the merge was pre-mature.  Will need to work on a branch, either here or perhaps stick to #69.  and once it is resolved, we can close both.

**Comment by petersilva** [comment]
oh... and backed out of the merge to master...
