### ISSUE TITLE
in the flow_test, binding to cpump exchange sometimes fails 

### ISSUE THREAD

**Issue by benlapETS** [MetPX/sarrac#62]
I am not sure what is going on here but the flow test reported this error for the xcvan config:
```
[ERROR] binding failed: server channel error 404h, message: NOT_FOUND - no exchange 'xcvan01'
```

**Comment by petersilva** [comment]
Normally, flows are well established over the long term.  The flow_test has to establish those flows
at the beginning.  When the flow tests start,  the publishers and consumers may be started at once. publishers declare the exchanges they publish do, consumers declare the queues they consume from.
If the subscriber gets there first, then it will try to bind to the exchange, but since the publisher isn't up yet, the exchange isn't declared yet.  so you get this error.  If you look in the log, not just the single error message, there should be a series of them followed by a INFO message like:
`
"queue %s bound with topic %s to %s\n"`

Indicating it looped until the binding succeeds.  It's an ERROR because it isn't functioning, until the INFO marks the correction.

This indicates a race condition of some kind on startup, which is harmless in practice.  However, there might be something we can do to get rid of it anyways... At one point, we used sr declare or sr setup to provide declarations before actually doing the startup... there might be some work to avoid binding in the declare or setup actions, only binding in start...

**Comment by petersilva** [comment]
didn't realize that it didn't recover binding failures! With v2.19.12b2, it now loops on binding failures, so this should be recovered automatically now.  Didn't do the subtopic None support there yet.

**Comment by petersilva** [comment]
with the recovery, I think this is addressed.
