### ISSUE TITLE
sr_cpump stops working on corrupt message

### ISSUE THREAD

**Issue by msaraga** [MetPX/sarrac#71]
Observed in flow test logs
```
2019-11-01 15:13:43,864 [ERROR] corrupted message, num_entries > 0 (2), but entries close to NULL ((nil)).
```
No logs follow...

**Comment by petersilva** [comment]
observations from experiments on this:

* It shows up in v03 message reception.  in the flow_test this show up in the winnowish configuration (xvan_f14 and xvan_f15)
*  tested with posts from python (shovel) and C (pump) implementations feeding this (converting a v02 datamart feed to v3), and the test on the consumer happens with messages created by both implementations.
* in a debugger, I can see the headers are corrupt.  It can crash immediately, or run for 10 minutes before the header corruption occurs.  no obvious pattern about the messages have corrupt headers.
* sr_audit restarts the pumps after they crash, and they seem to crash

implemented a work-around that just skips headers if they are corrupt.  It doesn't crash anymore... but I'm not super comfortable with this... would really like to understand the root cause.

**Comment by petersilva** [comment]
remove call to amqp_maybe_release_buffers, and the issue goes away... hmm... not an answer, but a big hint.
